### ISSUE TITLE
The interface is stored in the database

### ISSUE THREAD

**Issue by ArrorShine** [TomPallister/Ocelot#112]
Interfaces are stored in configuration files, some of which are inconvenient for the processing and interfacing of multiple systems. They want to configure the interface in the database and operate with the interface configuration

**Comment by TomPallister** [comment]
Hi @ArrorShine do you mean implementing a way to store the ocelot configuration in a database rather than in memory / flat file?

This is of course possible and I could work on it one day but I am still working on Ocelot clustering at the moment.

Please feel free to study the code and submit a PR for the feature if you have time!

**Comment by TomPallister** [comment]
Hi there, I'm closing this because it's been quite a few days since this was discussed and I am not planning to implement this feature myself anytime soon.

Sorry!!!

Thanks for your contribution though! :D
