### ISSUE TITLE
Fix Ocelot build pipeline

### ISSUE THREAD

**Issue by TomPallister** [TomPallister/Ocelot#130]
https://ci.appveyor.com/project/TomPallister/ocelot-fcfpb

 Cake.Json the bane of my life...

Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.Json'.

Happens locally and with AppVeyor..

**Comment by dbarkwell** [comment]
Update build.ps1 (https://github.com/cake-build/cake) and in build.cake add both:

#addin nuget:?package=Cake.Json
#addin nuget:?package=Newtonsoft.Json&version=9.0.1

**Comment by TomPallister** [comment]
@dbarkwell thanks I'll give this a shot!

**Comment by stuartsaltzman** [comment]
@TomPallister - I changed the version of  Newtonsoft.Json to **9.0.1** but I now receive a different error, details below. 

Error message: "The type 'Dictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'."

Caused by:  _ToDictionary()_  within method _PublishPackages_ on line 385 of cake.build. 

Workaround: As a workaround, I generated the dictionary by simply looping through the items rather than calling the extension method as shown below. I am unfamiliar with Cake (this is the first time I have worked with it) so maybe there is a an easier solution such as adding the correct assembly reference, upgrading the Cake version or changing the version of one of the addins/tools. 

Changed:
	var artifacts = System.IO.File
		.ReadAllLines(artifactsFile)
		.Select(l => l.Split(':'))
		.ToDictionary(v => v[0], v => v[1]);

To:

	var artifactsKeyValues = System.IO.File
		.ReadAllLines(artifactsFile)
		.Select(l => l.Split(':'));

	var artifacts = new Dictionary<string, string>();
	foreach (var element in artifactsKeyValues)
		artifacts.Add(element[0], element[1]);

**Comment by TomPallister** [comment]
@stuartsaltzman https://github.com/TomPallister/Ocelot/pull/132 fixed the build...give it a try.

@dbarkwell thanks for the help! Seems to have worked.

**Comment by stuartsaltzman** [comment]
@TomPallister - just pulled down your changes and gave it a try. Same error. Note, I am on a mac os.

Output from running ./build.sh is below. The only way I am able to remedy the problem is the workaround I described above. I also pulled down Cake.net's example template and tried the _.ToDictionary()_ extension and received the same error therefore the issue is unrelated to Ocelot. However, the build does not seem to run on macos - I wonder if other non-windows users are experiencing the same issue.

Output from running ./build.sh:
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Compiling build script...
Error: Error occurred when compiling build script: /Users/stuartsaltzman/Dev/src/dotnet/Ocelot/build.cake(378,25): error CS0012: The type 'Dictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by TomPallister** [comment]
@stuartsaltzman I have known it isnt working on mac for a while see [here](https://github.com/TomPallister/Ocelot/issues/98). Let's pick this up there. Ive pasted your comment on that issue!

**Comment by stuartsaltzman** [comment]
@TomPallister - The newly released Cake version 0.25.0 resolves the issue experienced when building on mac (mono) as described above. I tried building on mac using Cake v0.25.0 and it builds successfully without the workaround.

Cake 0.25.0 release notes (https://www.nuget.org/packages/Cake/0.25.0):
- ToDictionary on Mono causes "The type 'Dictionary<,>' is defined in an assembly that is not referenced"

**Comment by TomPallister** [comment]
@stuartsaltzman thank you very much!
