### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by gdyrrahitis** [TomPallister/Ocelot#131]
Hello,

I am experimenting with Ocelot these days. I tried Ocelot on an ASP.NET Core 1.1, with a 2.0 runtime.
I have declared the downstreams in localhost, all good so far. Testing in IIS Express from Visual Studio, seems to work just fine.
Then I publish to IIS. It still works, but the responses are slow, it might take many seconds to respond or just hangs, and there is not such performance issue with the standalone services, they are fast enough. I could not find something alerting enough in IIS.
Is anybody experiencing any similar issues?

VM: Windows Server 2008 R2
IIS: IIS 7
.NET: .NET Core 2.0 installed

**Comment by TomPallister** [comment]
@gdyrrahitis thanks for contributing! I've had this reported previously and the issue was logging out to the console. What kind of logging do you have Ocelot set up to use? If you set it to errors only and console it shouldn't be too slow!

It could also be something to do with IIS. I haven't tested Ocelot with IIS :( or it could just be Ocelot!

**Comment by gdyrrahitis** [comment]
I am following wiki's instructions on Startup. https://github.com/TomPallister/Ocelot/wiki/Startup

You say you haven't tested Ocelot with IIS. Do you suggest self hosting in a windows service? What is recommended, and working, for you?

**Comment by TomPallister** [comment]
@gdyrrahitis the startup adds console logging which is slow so that is probably why you are experiencing performance problems. The startup is just an example of how to get Ocelot up and running and is not recommended for production use. Consulting asp.net core docs should help with this! My apologies for any confusion!! :( 

I have hosted Ocelot using Azure web apps and AWS ElasticBeanstalk (assume IIS under the hood). Docker and a Linux daemon using nginx in front of kestrel.

Ocelot is currently just a nuget package because I don't want to have the responsibility of looking at hosting options! However it might be something in the future!

**Comment by gdyrrahitis** [comment]
Thanks for clearing this out.
There is definitely an issue with IIS + Kestrel. Might be the machine's setup/configuration at fault, I am not sure. I have to test it on my terminal as well. Logging has nothing to do with that. If I serve the application through Kestrel, the performance is fine.

I had to run the application with `dotnet` command, so Kestrel runs on port 5000 and add a reverse proxy rule on IIS. This works, but sucks, I mean, there is already support for IIS as reverse proxy, why is that problematic, I can't understand.
I suspect it might have to do with the version, maybe an update to .NET Core 2.0 will fix this. Good news is I see you are already on the move to migrate to 2.0.

I will investigate more and provide feedback, if any.

**Comment by TomPallister** [comment]
@gdyrrahitis yeh I think the issue is more to do with IIS and Kestrel than Ocelot itself...the application doesn't do anything special! There are quite a lot of posts online about IIS and Kestrel having slow performance.
