### ISSUE TITLE
could you change AddOcelot extension method IConfigurationRoot paramter to IConfiguration type ?

### ISSUE THREAD

**Issue by Eilyyyy** [TomPallister/Ocelot#166]
Why does `ocelot`'s extension method `AddOcelot` accept a parameter that it's type is IConfigurationRoot,  in this way i can only config in a single file, i want config like this 
![image](https://user-images.githubusercontent.com/9607459/33249013-02483934-d363-11e7-8b5a-c86f7e4f0024.png) so ,Could you change the ocelot extension method "AddOcelot" so that it accepts an "IConfiguration" parameter instead of an "IConfigurationRoot"?

This will make things easier if you need to write the configuration to appsettings.

**Comment by TomPallister** [comment]
@Eilyyyy thanks for creating this issue! Why do you want to do this rather than having a separate configuration.json file for Ocelot?

If I change it I will break the behaviour for people already using Ocelot.

The reason the configuration is not in the appsettings.json file is that I did not want to pollute it with Ocelot specific configuration. It's not really appsettings in my opinion.

I will look at an override that takes IConfiguration!

**Comment by TomPallister** [comment]
@Eilyyyy I have had a look at it and it's not something I'm going to work on at the moment. The configuration.json works for now and I can't see massive value in giving an option to have the Ocelot settings in appsettings.

If you want you could submit a pull request that adds this functionality.

Thanks again for opening the issue!

**Comment by Eilyyyy** [comment]
@TomPallister i don't think add a override that take IConfiguration is a good idea. it's make people be confused that two method take param so similar.
i think it will not break the behaviour of people already using Ocelot, because IConfigurationRoot is inherit from IConfiguration, of course, i will do more test and give you a feedback.

**Comment by TomPallister** [comment]
@Eilyyyy I don't think that it will be possible to do because in certain situations Ocelot writes to configuration.json. In some ways it is better to think of configuration.json as a database. 

configuration.json provides an object called FileConfiguration. This can also be provided by Consul and I am thinking about doing an SQL server & SQL lite version of the FileConfiguration provider.

I think it is definitely better to not have the Ocelot configuration in appsettings.json.

**Comment by TomPallister** [comment]
@Eilyyyy this is done in version 2.0.8

Sorry I did not realise what you wanted until I looked into the code more.
