### ISSUE TITLE
IRequestScopedDataRepository lifetime issue

### ISSUE THREAD

**Issue by awarrenlove** [TomPallister/Ocelot#169]
The IRequestScopedDataRepository dependency is registered by OcelotBuilder with a scoped lifetime. However, it is used by AspDotNetLoggerFactory, which is registered with a singleton lifetime.

The DI container in ASP.NET Core 1.x allowed this to happen, but ASP.NET Core 2.x throws a runtime exception when one dependency uses another with a smaller lifetime. It is a simple change to make IRequestScopedDataRepository a singleton, but that will make the name confusing so I'm not sure what you would prefer as the best course of action to fix this.

**Comment by TomPallister** [comment]
@awarrenlove thanks for helping out!

This whole part of Ocelot needs looking at tbh. How can I get a failing test for this? I would expect this to happen all the time but it does not fail for me :(

**Comment by awarrenlove** [comment]
I'm having a hard time simulating it as well. When I run the application, it throws an InvalidOperationException. When I set up the DI container using the OcelotBuilder and manually request the same service instance it resolves just fine. I'll keep working with it and update once I figure out a reproducible test.

**Comment by awarrenlove** [comment]
I found it. The problem is the newer project templates for ASP.NET Core 2 use WebHost.CreateDefaultBuilder, which sets ServiceProviderOptions.ValidateScopes to true for the Development environment. https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovideroptions.validatescopes?view=aspnetcore-2.0

I created a new test under your OcelotBuilderTests that demonstrates this problem. https://github.com/TomPallister/Ocelot/pull/171

**Comment by TomPallister** [comment]
@awarrenlove OK cool thanks for the failing test!

So I'm not sure what to do..

When I originally envisioned IRequestScopedDataRepository I was going to have something in memory per request to persist Ocelot specific data. In the end all I did was create HttpDataRepository (Should probably be called HttpContextRepository) and store the per request data on the HttpContext.Items dictionary. It's not ideal because this dictionary constraint is object and I wanted to use generics so I didn't have to cast. The idea being I would come back to it later and see if I could get something generic so I dont cast but as Ocelot grew I haven't got round to it yet!!!

Even if it is registered as a singleton it is still returning per request scoped data so I think its OK if that is the solution for now. What do you think? Do you want to change it to a singleton on your branch get the test passing and I'll merge it?

**Comment by TomPallister** [comment]
merged and fixed
