### ISSUE TITLE
How to support hostname on upstream path template? 

### ISSUE THREAD

**Issue by darting** [TomPallister/Ocelot#209]
Hi, just wonder how to support hostname on upstream path template since my case we have more than one domain point to same server. 

Thanks

**Comment by TomPallister** [comment]
@darting Thanks for your interest in the project!

I am not sure what you want to do!! You cannot have a hostname on the upstream path because the upstream path uses Ocelot's hostname. 

Think of the upstream path as being the url you would map to a controller in an asp.net webapi for example.

Hope this helps!

**Comment by darting** [comment]
Hi TomPallister, 

I want to use Ocelots as API gateway, and I want few domains point to it, let's say:

backoffice.mydomainA.com
back office.mydomainB.com
gameservice.mydomainA.com
gameservice.mydomianB.com

These domain all point same server which I used to host Ocelots, and forward requests to the real application. Currently I have no ideas how do it, any suggestions? Btw I was used traefix before it is handle this kind of case very well, thanks for your time.

**Comment by TomPallister** [comment]
@darting I think traefik is more suited to your use case.

Ocelot is meant to be more like azure, AWS, apigee style API gateways it is not really a service mesh. 

However you can use it for your scenario but you do not need to do anything with your clients other than point them at Ocelot. 

Once this is done you configure ReRoutes in Ocelot to point to your downstream services. Ocelot has no concept of specific clients at the moment. The ReRoutes in Ocelot then correspond to the downstream services and there routes.

**Comment by darting** [comment]
@TomPallister Is it possible to add one more options for ReRoutes, lets say **UpstreamHostName**:
```json
{
        "DownstreamPathTemplate": "/{everything}",
        "DownstreamScheme": "http",
        "DownstreamHost": "localhost",
        "DownstreamPort": 5000,
        "UpstreamPathTemplate": "/{everything}",
        "UpstreamHostName": "backoffice.domain.com"
}
```

**Comment by TomPallister** [comment]
@darting OK I understand now.

You want to be able to support multiple upstream paths for different clients.

OK it would be possible and would require some changes to how Ocelot matches a route. 

You can study the source code and try to implement this yourself or I will do it at some point in the future!

**Comment by TomPallister** [comment]
@darting I have had a look at this and Im not sure it will be possible without the client sending a referrer header or something.

When asp.net allows you to access the HttpRequest you cannot see the host name where it came from so I would not be able to identify the upstream host name. 

How did you set this up with Traefik?

**Comment by darting** [comment]
@TomPallister Sorry busy on others. In Traefik it can be configure using matcher of Frontends.
e.g. https://docs.traefik.io/basics/#examples

Docs:
https://docs.traefik.io/basics/#matchers

**Comment by darting** [comment]
Is it possible to get the host name from HttpRequest.Host property ?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequest.host?view=aspnetcore-2.0#Microsoft_AspNetCore_Http_HttpRequest_Host

**Comment by TomPallister** [comment]
@darting yes it could be but it must be set by the client otherwise it will default to Ocelot's host which is annoying. I guess I would just need to make it clear in the documentation if you use the feature then you must make sure the host header is set.

In the RFC for HTTP 1.1 it says Host is mandatory but I dont think anything in ASP.NET makes sure it is mandatory :( confusing!

**Comment by darting** [comment]
Hmm, got it. I do agreed just make it clear in the documentation. Thanks again :)

**Comment by TomPallister** [comment]
@darting sorry for being confused but wont the host header be set as the ocelot host address? I am studying host header this article explains better http://www.it-notebook.org/iis/article/understanding_host_headers.htm

e.g.

GET
/api/test
host: ocelot.com

Dont we want the origin header e.g.
/api/test
host: ocelot.com
origin: backoffice.mydomainA.com

In the first scenario Ocelot cannot identity different routes based on host ocelot.com because it will always be the same. Using the origin header ocelot can send the request to a different ReRoute.

Or are you expecting Ocelot to be running on the backoffice.mydomainA.com domain

e.g.

GET 
/api/test
host: backoffice.mydomainA.com

**Comment by darting** [comment]
@TomPallister 

Lets say we have domains:
- backofficeDomain.com
- gameserviceDomain.com

And I have a webserver with IP 192.168.0.1.
And I have one web application named backoffice and another web application named gameservice.

I want to host Ocelot in my webserver with the following ServerBindings:
- 192.168.0.1:80:www.backofficeDomain.com
- 192.168.0.1:80:www.gameserviceDomain.com

and also I will host backoffice on my webserver with:
- 127.0.0.1:5000

gameservice on my webserver with:
- 127.0.0.1:5001

so now if client send a http request:
```
GET / HTTP/1.1
Host: www.backofficeDomain.com
```
I want Ocelot forward this request to 127.0.0.1:5000 (backoffice)

 if client send a http request:
```
GET / HTTP/1.1
Host: www.gameserviceDomain.com
```
I want Ocelot forward this request to 127.0.0.1:5001 (gameservice)

I hope my explanation is clear :)

**Comment by TomPallister** [comment]
@darting yes I finally understand! 

I have never hosted Ocelot where I use multiple bindings on the web server!! This is why I couldn't understand what you wanted.

**Comment by TomPallister** [comment]
wait for release then close

**Comment by TomPallister** [comment]
@darting please get version 3.0.1 and try your scenario! Hopefully it will work.
