### ISSUE TITLE
How to use AllowedScopes?

### ISSUE THREAD

**Issue by FerAguilarR93** [TomPallister/Ocelot#231]
Hello, I´m using your API Gateway and is very Useful, I´m using my AuthenticationProvider and all works ok, but I have a question, in your manual test in configuration.json you have this:

**"AuthenticationOptions": {
        "AuthenticationProviderKey": "TestKey",
        "AllowedScopes": [
          "openid",
          "offline_access"
        ]
      }**

and my question is how to use AllowedScopes?... what values can it take and in which case would they be used?... Thanks in advance

**Comment by TomPallister** [comment]
@FerAguilarR93 thanks for your interest in the project!

If you set allowed scopes Ocelot will get all the user claims of the type scope and make sure that the user has all of the scopes in the list.

This is a way to restrict access to a ReRoute on a per scope basis.

Does that help?

**Comment by FerAguilarR93** [comment]
Yes it has been very helpful, thanks for your prompt response and willingness to help

**Comment by garybond** [comment]
@TomPallister I'm commenting here rather than opening a new issue, as I have the same question over clarification of this. I'm not sure the answer given, nor the documentation matches the actual functionality. The documentation clearly states that ALL of the scopes declared in the Route AllowedScopes should be present in the user's scope claim, however, as I understand the code [ScopesAuthoriser](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/Authorisation/ScopesAuthoriser.cs), it does an intersect of the two lists and an error is only thrown is if the count of matches is 0 (user has none of the required scopes).
The behaviour I am observing is that if you specify two scopes in Route AllowedScopes and the user only has one of them, authorisation succeeds, due to the use of Intersect, in contradiction to the documentation. Have I got this wrong?

**Comment by ggnaegi** [comment]
@raman-m, @garybond is imho right, the allowed scopes functionality doesn't work as explained by Tom, the ScopesAuthoriser class is doing an intersect of the two arrays / list. 
```c#
var matchesScopes = routeAllowedScopes.Intersect(userScopes);

            if (!matchesScopes.Any())
            {
                return new ErrorResponse<bool>(
                    new ScopeNotAuthorizedError($"no one user scope: '{string.Join(',', userScopes)}' match with some allowed scope: '{string.Join(',', routeAllowedScopes)}'"));
            }

            return new OkResponse<bool>(true);
```
https://ocelot.readthedocs.io/en/latest/features/authentication.html#allowed-scopes

> If you add scopes to AllowedScopes Ocelot will get all the user claims (from the token) of the type scope and make sure that the user has all of the scopes in the list.

The question is now the following, should we change the behavior or update the docs?

**Comment by raman-m** [comment]
> https://ocelot.readthedocs.io/en/latest/features/authentication.html#allowed-scopes
> 
> > If you add scopes to AllowedScopes Ocelot will get all the user claims (from the token) of the type scope and make sure that the user has all of the scopes in the list.
> 
> The question is now the following, should we change the behavior or update the docs?

@ggnaegi Don't read ReadTheDocs.io! This documentation is outdated!! We have some build error, or docs build should be performed manually.
The actual documentation locates in **develop** branch, the **docs** folder. ☝️

**Comment by ggnaegi** [comment]
@raman-m ok, my bad
https://github.com/ThreeMammals/Ocelot/blob/3b776a753cfecd17b70c91c8f3ea7e46ccb7de84/docs/features/authentication.rst#L172

> If you add scopes to AllowedScopes Ocelot will get all the user claims (from the token) of the type scope and make sure that the user has at least one of the scopes in the list.

**Comment by raman-m** [comment]
> @ggnaegi commented [on Oct 14](#issuecomment-1762279382)
> but what are the plans for the docs?

We've [released](../releases/tag/20.0.1) them together! 😄
