### ISSUE TITLE
How do you handle configuration for multiple environments.

### ISSUE THREAD

**Issue by charleslbryant** [TomPallister/Ocelot#249]
What is the best way to handle configurations for multiple environments. Say I have a Dev, Test, and Production environment and each one has a different base URL. How do you handle the configuration for multiple environments?

Awesome project.

**Comment by geffzhang** [comment]
API resource target request address, different deployment environment domain name is different, or domain name needs to support multiple, you can use the deployment environment variable implementation, such as:
To define a variable in a template variable in a deployment environment: domain = api.test.com
When creating a resource, the target request address is defined as: http://{stagevariables.domain}/get/tasks/12345/
When the resource is requested, the target address that the API gateway actually requests is http://api.test.com/get/tasks/12345/, and the {Stagevariables.domain} in the destination address is replaced with the corresponding value in the deployment environment variable

This configuration is not currently supported

**Comment by TomPallister** [comment]
@charleslbryant thanks for your interest in the project.

Like any other .net core project ocelot supports the following.

```csharp
                        config.AddJsonFile($"configuration.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true)
```

The EnvironmentName property is taken from the ASPNETCORE_ENVIRONMENT environmental variable which must be set on the relative environment. 

This means you can have:

configuration.dev.json
configuration.qa.json
configuration.staging.json
configuration.production.json
etc

There used to be a bug with this but it was fixed by a contributor a while ago so it should work fine! Let me know if you have any problems.

**Comment by TomPallister** [comment]
@geffzhang does asp.net automatically support swapping placeholders from IOptions<T> with environmental variables? If not this is a feature we would need to implement! 

At the moment I am happy having multiple configuration.json (see comment above) and don't have time to implement this. However if you did have time that would be awesome!

**Comment by charleslbryant** [comment]
That worked thanks.

**Comment by TomPallister** [comment]
Awesome!

**Comment by murdockpeter** [comment]
Tom P. - Thank you for your suggestions above (two years later - but never too late!). This post helped me out greatly today. Ocelot is wonderful. I assume there is no new and easier way to accomplish this in one ocelot.json file?
