### ISSUE TITLE
I updated the code for you, run the test, there are three tests pass

### ISSUE THREAD

**Issue by geffzhang** [TomPallister/Ocelot#56]
Ocelot.IntegrationTests have three test not pass,see pic
![integrationtestsadministration](https://cloud.githubusercontent.com/assets/439390/23338490/9d752cd0-fc47-11e6-83c8-bc104785048d.png)

**Comment by TomPallister** [comment]
@geffzhang this is because the integration tests need you to set environmental variables.

I have updated readme in this commit to explain https://github.com/TomPallister/Ocelot/commit/1d216f686371bd3055dd949e03b3e2d72dfc640e

It would be better to have the test set them up but I haven't found a way of doing this yet.
