### ISSUE TITLE
ResponderMiddleware will never set a 500 response code

### ISSUE THREAD

**Issue by MarcDenman** [TomPallister/Ocelot#66]
[ResponderMiddleware.cs](https://github.com/TomPallister/Ocelot/blob/c09cec67c63a543eefbfbffafff3c2662b356c85/src/Ocelot/Responder/Middleware/ResponderMiddleware.cs#L59) looks as if it can set a 500 to be returned, however, the implementation of [ErrorsToHttpStatusCodeMapper](https://github.com/TomPallister/Ocelot/blob/c09cec67c63a543eefbfbffafff3c2662b356c85/src/Ocelot/Responder/ErrorsToHttpStatusCodeMapper.cs) creates a new OkResponse and does not pass the list of errors through. 

As such, when `ResponderMiddleware` calls [IsError](https://github.com/TomPallister/Ocelot/blob/c09cec67c63a543eefbfbffafff3c2662b356c85/src/Ocelot/Responses/Response.cs#L20) `false` will always be returned.

I am 85% sure what I have said above is correct, as I am still learning the codebase, happy to PR though if I can be pointed in the correct direction.

**Comment by TomPallister** [comment]
@MarcDenman you are correct, I would change the ErrorsToHttpStatusCodeMapper to not return with a wrapped Response<T> value. Would be great if you could make that change otherwise just leave it here and ill get to it. Good spot.

Really grateful for the assistance. I know from experience getting a second pair of eyes on my code will pick up these kind of issues so much appreciated.

**Comment by MarcDenman** [comment]
Excellent, not a problem, happy to help out :) 

I have made a PR with the changes and fixed up the unit tests

**Comment by TomPallister** [comment]
@MarcDenman merged PR closing issue!
